version: '3'


volumes:
  dbdata6:

services:
  mongodb:
    image: mongo:latest
    volumes:
      - dbdata6:/data/db


  backend:
    build: ./
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - 127.0.0.1:8000:8000